In [1]:
import matplotlib.pyplot as plt
import cv2

from byotrack import Video, VideoTransformConfig

from byotrack.implementation.detector.stardist import StarDistDetector

import skimage.io as iio
from byotrack.video.transforms import ChannelSelect, ChannelAvg, ScaleAndNormalize 
from PIL import Image
import numpy as np #can switch this out for pytorch at somepoint - notation is identical
from roifile import ImagejRoi, ROI_TYPE, ROI_OPTIONS

icy_path = "/home/noah/Documents/icy-2.4.2.0-all"
tifpath = '/home/noah/Desktop/cellsegtest/segTestNew/shortStack_adjusted' #path to sequence of tiff files

2023-07-13 17:26:38.806906: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-13 17:26:38.832608: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-13 17:26:39.310737: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
#reader funtion for tif sequences 

def Read_Data_TIFseq(vid_path):
    # positions = (pd.read_csv(csv_path,usecols=['TrackID','t','x','y'])).values
    vid = iio.ImageCollection(vid_path + '/*.tif').concatenate() #concatonate to numpyarray
    # red_vid = iio.ImageCollection(red_vid_path + '/*.tif')
    vid = vid.reshape(vid.shape[0], vid.shape[1], vid.shape[2], 1)
    #vid = np.asarray([csbdeepNormaliser(frame) for frame in vid])
    return vid

video = Read_Data_TIFseq(tifpath)

# normalize video
mini = np.quantile(video, 0.005)
maxi = np.quantile(video, 0.999)

np.clip(video, mini, maxi, video)
video = (video - mini) / (maxi - mini)

In [3]:
model_path = "/home/noah/Desktop/STARDIST_CONFOCAL/NEWEST TdT MODELS/10X_IMAGES_ONLY"
detector = StarDistDetector(model_path, batch_size=5)

Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.592132, nms_thresh=0.3.


stardist.py (41): Current implementation do not support batch size greater than 1 and will iterate image by image
2023-07-13 17:26:40.065825: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2023-07-13 17:26:40.065846: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: NoahComp
2023-07-13 17:26:40.065849: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: NoahComp
2023-07-13 17:26:40.065901: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: 525.125.6
2023-07-13 17:26:40.065911: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 525.116.4
2023-07-13 17:26:40.065913: E tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:312] kernel version 

In [4]:
#run stardist directly
# image = video_norm[0]
image = video[0]
segmentation, data = detector._model.predict_instances(image, prob_thresh=detector.prob_threshold, nms_thresh=detector.nms_threshold, predict_kwargs={"verbose": 0})

In [5]:
def coordReshaper(coords): #reshaping for use with imageJ rois
    coords_reshaped = []
    for i in range(len(coords[0])):
        xdata = coords[0][i]
        ydata = coords[1][i]
        coords_reshaped.append([ydata,xdata])
    return coords_reshaped

allROIs = []
for rois in data["coord"]:
    roishaped = coordReshaper(rois)
    allROIs.append(roishaped)

In [6]:
data["coord"][0]

array([[594.     , 594.9338 , 595.64886, 596.71906, 597.2081 , 598.07056,
        597.7834 , 598.21094, 598.6297 , 598.6633 , 598.33496, 598.79596,
        598.91797, 598.71466, 597.6204 , 595.83746, 594.     , 592.36725,
        591.243  , 590.6388 , 590.6154 , 590.1142 , 590.5464 , 589.9496 ,
        589.81256, 589.8818 , 590.18317, 590.0028 , 590.71857, 591.1401 ,
        592.26276, 593.0278 ],
       [348.9487 , 348.6944 , 347.9807 , 348.06934, 347.20813, 346.71988,
        345.56714, 344.83762, 344.     , 343.07242, 342.2044 , 340.79544,
        339.082  , 336.94397, 335.25958, 334.76236, 334.607  , 335.79175,
        337.344  , 338.96964, 340.61545, 341.4036 , 342.56946, 343.19434,
        344.     , 344.81915, 345.581  , 346.67084, 347.2814 , 348.28018,
        348.19406, 348.88757]], dtype=float32)

In [7]:
def coordReshaper_CV_contours(coords):

    '''
    Reshape contours generated by StarDist for use with openCV's display contours function
    '''

    coords_reshaped = []
    for contour in np.flip(coords): #hard to find this solution - coords need to be flipped, they are read clockwise by openCV and I guess this is not how they are written by StarDist. Results in contours plotted transposed from desired without flipping array.:)
        for i in range(len(contour[0])):
            coords_reshaped.append([contour[0][i], contour[1][i]])
    
    cv_format_contours = (np.array(coords_reshaped).reshape((-1,1,2)).astype(np.int32)) #https://stackoverflow.com/questions/14161331/creating-your-own-contour-in-opencv-using-python
    return cv_format_contours

cvContours = coordReshaper_CV_contours(data["coord"])



In [13]:
blankimage = np.zeros(image.shape, dtype='uint8')
print(blankimage.shape)
contourImage = image.copy()

for contour in cvContours:
    cv2.drawContours(contourImage, [contour], 0, (1,0,0),1)
cv2.imshow("blank", contourImage)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1024, 1024, 1)


QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to tar

In [ ]:
cvContours[2]

In [ ]:
# from imagej import IJ
# from ij import ImagePlus
# from ij.gui import Roi, PointRoi, PolygonRoi
# from ij.plugin.frame import RoiManager

In [ ]:
ijrois = []
for roi in allROIs:
    roimask = ImagejRoi.frompoints(roi)
    roimask.roitype = ROI_TYPE.POLYGON
    roimask.options |= ROI_OPTIONS.SHOW_LABELS
    # roimask.plot()
    # print(roimask.subpixelresolution)
    ijrois.append(roimask)
# plt.show()

In [ ]:
def plot_image_overlays(image, overlays, **kwargs):
    """Plot image and overlays (bytes) using matplotlib."""
    fig, ax = plt.subplots(figsize = (60,60))
    ax.imshow(image, cmap='gray')
    if not isinstance(overlays, list):
        overlays = [overlays]
    for overlay in overlays:
        # roi = ImagejRoi.frombytes(overlay)
        roi = overlay
        roi.plot(ax, **kwargs)
    plt.show()

In [ ]:
type(ijrois[0])

In [ ]:
plot_image_overlays(image, ijrois)
print(data.keys())

In [15]:
img_n = cv2.normalize(src=image, dst=None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8U)

In [16]:
##cv contours
# image32 = image2.astype('uint8') #opencv needs float32, images loaded as float64 here :)
imagecv = cv2.cvtColor(img_n, cv2.COLOR_GRAY2BGR)

In [ ]:
contours,_ = cv2.findContours(imagecv[:,:,0],cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

In [ ]:
np.shape(contours)

In [ ]:
data['coord'][0]

In [ ]:
contours[0][0][0][0]

In [ ]:
cvContours[0][0]

In [ ]:
plt.imshow(imagecv)
print(imagecv.shape)
print(imagecv.dtype)

In [17]:
mask = np.zeros(imagecv.shape, np.uint8)
image_contours = imagecv.copy()
# Iterate over all contours
for i,c in enumerate(cvContours):
    try:
        # Find mean colour inside this contour by doing a masked mean
        # mask = np.zeros(image_contours.shape, np.uint8)
        # cv2.drawContours(mask,[c],-1,255, -1)
        # DEBUG: cv2.imwrite(f"mask-{i}.png",mask)
        # print(':)')
        # mean,_,_,_ = cv2.mean(imagecv, mask=mask)
        # DEBUG: print(f"i: {i}, mean: {mean}")

        # Get appropriate colour for this label
        # label = 2 if mean > 1.0 else 1
        colour = (0,255,255)
        # DEBUG: print(f"Colour: {colour}")
        print(c)

        # Outline contour in that colour on main image, line thickness=1
        cv2.drawContours(image_contours,[c],-1,colour,1)
    except Exception as e:
        print(e)

        break
try:
    cv2.namedWindow('contour', cv2.WINDOW_NORMAL)
    cv2.imshow('contour',image_contours) 

    cv2.waitKey(0)
    cv2.destroyAllWindows()
except Exception as e:
    print(e)
    cv2.destroyAllWindows()

# try:
#     cv2.drawContours(mask,[c],-1,255, -1)
# except Exception as e:
#     print(e)

[[654 439]]
[[653 439]]
[[653 438]]
[[653 438]]
[[653 438]]
[[652 438]]
[[652 437]]
[[652 437]]
[[651 437]]
[[651 437]]
[[650 437]]
[[649 437]]
[[648 437]]
[[648 438]]
[[648 439]]
[[648 440]]
[[648 440]]
[[648 441]]
[[648 442]]
[[648 443]]
[[649 443]]
[[650 443]]
[[651 443]]
[[652 444]]
[[652 443]]
[[653 443]]
[[654 443]]
[[654 442]]
[[654 441]]
[[654 440]]
[[654 440]]
[[654 440]]
[[519 419]]
[[519 419]]
[[519 418]]
[[519 418]]
[[519 418]]
[[518 418]]
[[518 417]]
[[518 417]]
[[517 417]]
[[517 417]]
[[516 417]]
[[515 417]]
[[514 417]]
[[514 418]]
[[514 419]]
[[513 420]]
[[514 420]]
[[514 421]]
[[513 422]]
[[514 423]]
[[515 423]]
[[516 423]]
[[517 423]]
[[518 423]]
[[518 423]]
[[519 422]]
[[519 422]]
[[520 422]]
[[520 421]]
[[519 420]]
[[520 420]]
[[519 420]]
[[ 77 353]]
[[ 77 352]]
[[ 77 351]]
[[ 77 350]]
[[ 76 350]]
[[ 75 350]]
[[ 74 350]]
[[ 74 350]]
[[ 73 350]]
[[ 72 351]]
[[ 72 351]]
[[ 71 351]]
[[ 71 352]]
[[ 71 353]]
[[ 71 353]]
[[ 71 354]]
[[ 71 354]]
[[ 72 354]]
[[ 71 355]]
[[ 7

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to target thread (0x55645dedcd40)

QObject::moveToThread: Current thread (0x55645dedcd40) is not the object's thread (0x55645dd4d270).
Cannot move to tar

In [ ]:
cv2.namedWindow('contour', cv2.WINDOW_NORMAL)
cv2.imshow('contour', imagecv)
cv2.waitKey(0)
  
# closing all open windows
cv2.destroyAllWindows()

In [ ]:
#evaluate model paramters on data

# Do not run this cell in order to keep the defaults prob_thresh and nms_thresh

#TODO: add roi funtionality to this so plotting shows mask over image (better evaluation) Will need to edit both stardist detector and the detector class .detect() function to include polygon data and add imageJ ROI code
vidCopy = video[0:50] #test batch
scale = 1

global frameID
frameID = 0
frame = video[frameID]
h, w = frame.shape[0:2]
global mask_glob
detection_zero = detector.run([vidCopy[frameID]])
mask_glob = (detection_zero[frameID].segmentation.numpy() != 0).astype(np.uint8) * 255

# window_name = 'Frame', f'Frame {frameID} / {len(detections_sequence_test)} - Number of detections: {len(detections_sequence_test[i])}'
window_name = 'Paramater Test - Segmentation   (Press Q to Quit)'

try:

    #create and rescale window
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(window_name, h*scale, w*scale)

    #Frame Trackbar
    def update_frame(x): #callback function for trackbar - default argument is the position of the track bar
        detections = detector.detect(vidCopy[x][None, ...])
        global mask_glob
        mask_glob = (detections[0].segmentation.numpy() != 0).astype(np.uint8) * 255
    cv2.createTrackbar('Frame',window_name,0,len(vidCopy)-1,update_frame)

    #Probability Trackbar
    def update_probability_threshold(x):
        detector.prob_threshold = (x+1)/100 
        update_frame(frameID)
    cv2.createTrackbar('Probability Threshold', window_name, 0, 99, update_probability_threshold)

    #Overlap Trackbar
    def update_overlap_threshold(x):
        detector.nms_threshold = (x+1)/100
        update_frame(frameID)
    cv2.createTrackbar('Overlap Threshold', window_name, 0, 99, update_overlap_threshold)

except Exception as e:
    print(e)


while True:
    try:

        frameID = cv2.getTrackbarPos('Frame',window_name)
        # cv2.imshow(window_name, video[frameID])
        cv2.imshow(window_name, mask_glob)

        probabilityThreshold = cv2.getTrackbarPos('Probability Threshold', window_name)/100
        nmsThreshold = cv2.getTrackbarPos('Overlap Threshold', window_name)/100

        #exit on q
        if cv2.waitKey(5) == ord('q'):
            # press q to terminate the loop
            cv2.destroyAllWindows()
            break

    except Exception as e:
        print(e)
        cv2.destroyAllWindows()
        break
    
cv2.destroyAllWindows()
print('Prob: ', probabilityThreshold)
print('nms: ', nmsThreshold)

In [ ]:
from roifile import ImagejRoi, ROI_TYPE, ROI_OPTIONS
roi = ImagejRoi.frompoints(coords)
roi.roitype = ROI_TYPE.POLYGON
roi.options |= ROI_OPTIONS.SHOW_LABELS

In [ ]:
#reader funtion for tif sequences - handles reshaping and normalising (using the stardist recommended normaliser) (doesn't seem to perform that well)
from csbdeep.utils import normalize as csbdeepNormaliser
    
def Read_Data_TIFseq(vid_path):
    # positions = (pd.read_csv(csv_path,usecols=['TrackID','t','x','y'])).values
    vid = iio.ImageCollection(vid_path + '/*.tif').concatenate() #concatonate to numpyarray #not concatenating allows for dynamic loading
    # red_vid = iio.ImageCollection(red_vid_path + '/*.tif')
    vid = vid.reshape(vid.shape[0], vid.shape[1], vid.shape[2], 1)
    normalisedVid = np.asarray([csbdeepNormaliser(frame) for frame in vid])
    return normalisedVid

video = Read_Data_TIFseq(tifpath)

In [ ]:
import colorsys
from scipy.ndimage.morphology import binary_dilation, binary_erosion
from skimage.morphology import disk
import random
import pandas as pd
from matplotlib.ticker import NullLocator

In [ ]:
#vis from cellseg

def get_bounding_box(masks):
    indices = np.where(masks != 0)
    values = masks[indices[0], indices[1]]
    maskframe = pd.DataFrame(np.transpose(np.array([indices[0], indices[1], values]))).rename(columns = {0:"y", 1:"x", 2:"id"})
    bb_mins = maskframe.groupby('id').agg({'y': 'min', 'x': 'min'}).to_records(index = False).tolist()
    bb_maxes = maskframe.groupby('id').agg({'y': 'max', 'x': 'max'}).to_records(index = False).tolist()
    
    return bb_mins, bb_maxes



def compute_snippet_bounds(minY, minX, maxY, maxX, Y, X):
    if minX < 0: minX = 0
    if minY < 0: minY = 0
    if maxX >= X: maxX = X - 1
    if maxY >= Y: maxY = Y - 1
        
    return minY, minX, maxY, maxX


def extract_snippet(Y, X, masks, mins, maxes):
    
    minY, minX, maxY, maxX = compute_snippet_bounds(mins[0] - 1, mins[1] - 1, maxes[0] + 1, maxes[1] + 1, Y, X)
        
    return masks[(minY):(maxY), (minX):(maxX)], minY, minX, maxY, maxX

def get_mask_ids(masks):
    maskids = list(np.unique(masks))
    maskids.remove(0)
    maskids.sort()
    
    return maskids

def random_colors(N, bright=True):
    """
    Generate random colors.
    To get visually distinct colors, generate them in HSV space then
    convert to RGB.
    """
    brightness = 1.0 if bright else 0.7
    hsv = [(i / N, 1, brightness) for i in range(N)]
    colors = list(map(lambda c: colorsys.hsv_to_rgb(*c), hsv))
    colors = [(int(i[0] * 255), int(i[1] * 255), int(i[2] * 255)) for i in colors]
    random.shuffle(colors)
    return colors

def generate_mask_outlines(masks):
    
    #first compute bounding boxes
    maskids = get_mask_ids(masks)
    num_masks = len(maskids)

    bb_mins, bb_maxes = get_bounding_box(masks)

    Y, X = masks.shape

    output_im = np.zeros(masks.shape, dtype = np.uint32)

    struc = disk(1)
    for i, maskid in enumerate(maskids):

        currreg, minY, minX, maxY, maxX = extract_snippet(Y, X, masks, bb_mins[i], bb_maxes[i])

        mask_snippet = (currreg == maskid)
        interior = binary_erosion(mask_snippet, struc)
        boundary = mask_snippet ^ interior

        pix_to_update = np.nonzero(boundary)

        pix_X = np.array([min(j + minX, X) for j in pix_to_update[1]])
        pix_Y = np.array([min(j + minY, Y) for j in pix_to_update[0]])

        output_im[pix_Y, pix_X] = maskid

    return output_im
    
def overlay_outlines_and_save(image, masks, outputpath, figsize, colors = None):
    
    auto_show = False
    _, ax = plt.subplots(1, figsize=figsize)

    maskids = get_mask_ids(masks)
    num_masks = len(maskids)

    # Generate random colors
    colors = colors or random_colors(num_masks)

    bb_mins, bb_maxes = get_bounding_box(masks)

    #rgb_im = cv2.cvtColor(nimage, cv2.COLOR_GRAY2RGB)
    rgb_im = image

    rgb_im = rgb_im.astype(np.uint8)

    Y, X = masks.shape

    for i, maskid in enumerate(maskids):

        currreg, minY, minX, maxY, maxX = extract_snippet(Y, X, masks, bb_mins[i], bb_maxes[i])
        mask_snippet = (currreg == maskid)


        color = colors[i]
        #if i < 10:
        #    print(color)
        #    plt.imshow(mask_snippet)
       #     plt.show()
       #     plt.close()
        pix_to_update = np.nonzero(mask_snippet)

        #minY, minX, maxY, maxX = compute_snippet_bounds(bb_mins[i][0] - 1, bb_mins[i][1] - 1, bb_maxes[i][0] + 1, bb_maxes[i][1] + 1, Y, X)

        pix_X = np.array([min(j + minX, X) for j in pix_to_update[1]])
        pix_Y = np.array([min(j + minY, Y) for j in pix_to_update[0]])

        rgb_im[pix_Y, pix_X, :] = color
        #rgb_im[pix_Y, pix_X, 1] = 255
        #rgb_im[pix_Y, pix_X, 2] = 255

    ax.axis('off')
    img = ax.imshow(rgb_im)
    # This is needed to remove all whitespace
    plt.gca().set_axis_off()
    plt.subplots_adjust(top = 1, bottom = 0, right = 1, left = 0, 
                hspace = 0, wspace = 0)
    plt.margins(0,0)
    plt.gca().xaxis.set_major_locator(NullLocator())
    plt.gca().yaxis.set_major_locator(NullLocator())
    plt.savefig(outputpath, dpi=75)
    plt.close()

In [ ]:
def maskplotter(image, segmentation, colors = None):

    # image=image.reshape(image.shape[0], image.shape[1])
    masks = segmentation
    maskids = get_mask_ids(masks)
    num_masks = len(maskids)

    # Generate random colors
    colors = colors or random_colors(num_masks)

    bb_mins, bb_maxes = get_bounding_box(masks)

    #rgb_im = cv2.cvtColor(nimage, cv2.COLOR_GRAY2RGB)
    rgb_im = image

    rgb_im = rgb_im.astype(np.uint8)
    print(rgb_im.shape)

    Y, X = masks.shape

    for i, maskid in enumerate(maskids):

        currreg, minY, minX, maxY, maxX = extract_snippet(Y, X, masks, bb_mins[i], bb_maxes[i])
        mask_snippet = (currreg == maskid)


        color = colors[i]
        #if i < 10:
        #    print(color)
        #    plt.imshow(mask_snippet)
        #     plt.show()
        #     plt.close()
        pix_to_update = np.nonzero(mask_snippet)

        #minY, minX, maxY, maxX = compute_snippet_bounds(bb_mins[i][0] - 1, bb_mins[i][1] - 1, bb_maxes[i][0] + 1, bb_maxes[i][1] + 1, Y, X)

        pix_X = np.array([min(j + minX, X) for j in pix_to_update[1]])
        pix_Y = np.array([min(j + minY, Y) for j in pix_to_update[0]])

        rgb_im[pix_Y, pix_X, :] = color

    return rgb_im

In [ ]:
dummy = np.zeros(image.shape)
img2 = cv2.merge((dummy,image,dummy))

In [ ]:
plt.imshow(img2)
plt.show()

In [ ]:
mask = (segmentation != 0).astype(np.uint8) * 255
masksim  = generate_mask_outlines(mask)
colorMaskIm = maskplotter(img2, mask)

In [ ]:
import tifffile
path = '/home/noah/Desktop/cellsegtest/segTestNew/shortStack_adjusted/camera2_NDTiffStack0002.tif'
image = np.array(tifffile.imread(path))
image = image.reshape(image.shape[0], image.shape[1], 1)
print(image.shape)
shape = image.shape
SHAPE = (shape[1], shape[2], shape[0])
image = np.transpose(image, (1, 2, 0))
image = image.reshape(SHAPE)

image.shape



In [ ]:
overlay_outlines_and_save(image, mask, '/home/noah/Documents/NoahT2022/CodeRepos/Utopia/ExampleData', (30,30), colors = None)

In [ ]:
_, ax = plt.subplots(1)
ax.axis('off')
img = ax.imshow(colorMaskIm)
# This is needed to remove all whitespace
plt.gca().set_axis_off()
plt.subplots_adjust(top = 1, bottom = 0, right = 1, left = 0, 
            hspace = 0, wspace = 0)
plt.margins(0,0)
plt.gca().xaxis.set_major_locator(NullLocator())
plt.gca().yaxis.set_major_locator(NullLocator())
# plt.savefig(outputpath, dpi=75)
plt.show()

In [ ]:
newim = masksim + image.reshape(image.shape[0], image.shape[1])
print(masksim.shape)
print(image.shape)
print(newim.shape)
plt.imshow(newim)
plt.axis('off')
plt.show()

In [ ]:
imgmask = cv2.merge((newim,dummy,dummy))
plt.imshow(imgmask)
plt.show()

In [ ]:
idx=~(masksim==0)
# newim = np.where(idx, image[::,0], image[::,0])
# newim2 = np.putmask(image[::,0], idx, 255)

indx = idx.nonzero()
newim3 = image.reshape(image.shape[0], image.shape[1])
newim3 = img2
print(newim3.shape)
newim3[indx][2] = 0.5
plt.imshow(newim3[::])
plt.show()

print(newim3.max())
print(newim3.shape)


In [ ]:
newim.shape
plt.imshow(idx)
idx

In [ ]:
plt.imshow(newim)